version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: skill-link-database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Shankar07
      POSTGRES_DB: skill_link_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: